### ISSUE TITLE
Stable version release

### ISSUE THREAD

**Issue by Sundareswar23** [espressif/esp-rainmaker#255]
### Is your feature request related to a problem?

A stable version is not available in rainmaker. sometimes the build are failing. For time being we need to move the git HEAD to use correct build. Please do release a stable

**Comment by shahpiyushv** [comment]
RainMaker primarily relies on stability of ESP IDF releases. Internal CIs verify that the git head compiles with release/v4.1, release/v4.2, release/v4.3, release/v4.4, release/v5.0 and release/v5.1. Compilation errors typically are seen due to incorrect usage or missing dependencies (especially, not synchronising git submodules). So atleast in the context of this particular issue (sometimes the build are failing), even a tagged release wouldn't have helped. We will consider if we really need releases for rainmaker, considering that it actually depends on releases of the rainmaker backend, skills, phone apps and esp idf, and update accordingly.
